### PR TITLE
Progress on 3D

### PR DESCRIPTION
**Pull request by hannesbrandt**
We continue translating fclaw2d files to 3D.
We add fclaw3d_exchange, fclaw3d_options and fclaw3d_patch.
The 3D functions that exclusively exist in 3D (e.g. functions dealing with edges) are defined in fclaw3d_*.c.
The 3D functions that have a 2D version as well are defined implicitly by including fclaw2d_*.c and fclaw2d_to_3d.h (which redefines fclaw2D function, typedef, macro and enum names to their fclaw3D version)  in fclaw3d_*.c.
3D Adaptions to the 2D version of a function are done by use of macros and #ifdef P4_TO_P8 in the fclaw2d_*.c definition.
In fclaw3d_patch further 3D exclusive functions (like fclaw3d_patch_copy_edge) might be  desired, that still need to be implemented.

We start a 3D swirl example in applications/clawpack/advection/p8/.
The example already creates a global_t and a domain that is either a 3D unit cube or a 3D brick.
We do not yet call vtables_initialize, initialize, run and finalize, since further code adaptions to 3D (translation of initialize/finalize, loops over edges in fclaw2d_convenience.c,...)  are necessary for this.

We temporarily disable the toplevel Cudaclaw options in configure.ac (see Issue #263).

### CODE REVIEW

**Comment by donnaaboise** [comment]
This is a great start!   Thanks for all of your work on this 3d.

**Comment by cburstedde** [comment]
@scottaiton do you think there is a simple way to make the CI run without the cuda call in configure.ac?

**Comment by scottaiton** [comment]
It seems like there should be a way to get it working without cuda call. I'll look into it today and see if I can get it working.

**Comment by scottaiton** [comment]
The bootstrap script for autotools has been throwing an error message about cuda ever since we added the cuda stuff. It's unreleated to 3d, but Carsten want's to get it fixed in this pull request.

**Comment by scottaiton** [comment]
@cburstedde I got it to work without the `check_cuda` script. I pushed the changes to the `feature-3d` branch of the main repository.

**Pull request merged**
